name: GitHub Actions Demo
on: 
  push:
    branches: [main]
    paths-ignore: [.github/**]
  pull_request:
    branches: [main]
  schedule:
    - cron: '15 6 * * 0'

jobs:
  Build:
    name: Build
    run-name: Build
    runs-on: unbuntu-latest
    steps:
      - run: |
        echo "The jow was trigger by event: ${{ github.event_name }}"
        echo "The name of your branch is ${{ github.ref }} and your repository is ."

      - name: Checkout
        uses: ctions/checkout@v4

      - name: list file in the repository
        run: |
          echo " the repo is ${{ github.repository }} "
          tree
        
      
