name: GitHub Actions Demo
on: 
  push:
    branches: [main]
    paths-ignore: [.github/**]
  pull_request:
    branches: [main]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:

jobs:
  Build:
    name: Build   
    runs-on: unbuntu-latest
    steps:
      - run: |
          echo "The job was trigger by event: ${{ github.event_name }}"
          echo "Thename of your beanch is ${{ github.ref }}"

      - name: Checkout
        uses: ctions/checkout@v4

      - name: list file in the repository
        run: |
          echo " the repo is ${{ github.repository }} "
          tree
        
      
