name: Reusable workflow
on:
  workflow_call:
    inputs:
       who-to-greet:
        description: 'A user passed from the caller workflow'
        default: 'Wrold'
        required: false
        type: string
    outputs:
      current-time:
        description: 'The time when greeting.'
        value: ${{ jobs.reusable-job.outputs.current-time }}
jobs:
  reusable-job:
    runs-on: ubuntu-latest
    steps:
      - name: Just echo 
        run: echo "Hello ${{ inputs.who-to-greet }}"
      - name: Set time
        id: timestep
        run: echo "time=$(date)" >> $GITHUB_OUTPUT
    outputs:
      current-time: ${{ steps.timestep.outputs.time }}
        
